# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-14 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FichaEmergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_e', models.DateField(auto_now=True)),
                ('hora', models.TimeField()),
                ('telefono', models.CharField(max_length=10)),
                ('alerta', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('coorX', models.FloatField()),
                ('coorY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retro_A', models.CharField(max_length=100)),
                ('fecha_r', models.DateField(auto_now=True)),
                ('hora', models.TimeField()),
                ('idemrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FichaEmergencia', to='Myapi.FichaEmergencia')),
                ('idestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='Myapi.Estado')),
            ],
        ),
    ]
