# Generated by Django 2.2.7 on 2019-12-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FichaEmergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=30)),
                ('telefono', models.CharField(default='', max_length=10)),
                ('tipollamada', models.CharField(choices=[(1, 'Celular'), (2, 'Telefono Fijo')], default=1, max_length=10)),
                ('fecha_e', models.DateField()),
                ('hora', models.TimeField()),
                ('provincia', models.CharField(default='', max_length=25)),
                ('canton', models.CharField(default='', max_length=30)),
                ('direccionReporte', models.CharField(default='', max_length=50)),
                ('direccionIncidente', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('operador', models.CharField(default='', max_length=50)),
                ('reportador', models.CharField(default='', max_length=50)),
                ('alerta', models.CharField(choices=[(1, 'Clave Amarilla'), (2, 'Clave Roja')], default=3, max_length=30)),
                ('coorX', models.FloatField()),
                ('coorY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=100)),
                ('institucion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Institucion', to='Myapi.Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('institucion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapi.Institucion')),
                ('recurso', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Recurso', to='Myapi.Recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retro_A', models.CharField(max_length=100)),
                ('fecha_r', models.DateField()),
                ('hora', models.TimeField()),
                ('idemrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FichaEmergencia', to='Myapi.FichaEmergencia')),
                ('idestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='Myapi.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionEmergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='Myapi.Usuario')),
                ('emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FichEmergencia', to='Myapi.FichaEmergencia')),
            ],
        ),
    ]
