# Generated by Django 2.2.7 on 2020-01-10 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retroalimentacion',
            old_name='idemrg',
            new_name='emergencia',
        ),
        migrations.RemoveField(
            model_name='retroalimentacion',
            name='fecha_r',
        ),
        migrations.AddField(
            model_name='retroalimentacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retroalimentacion',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retroalimentacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporta', to=settings.AUTH_USER_MODEL),
        ),
    ]
