# Generated by Django 2.2.7 on 2020-01-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0002_auto_20200110_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroalimentacion',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
