# Generated by Django 2.2.7 on 2019-12-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0003_auto_20191216_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaemergencia',
            name='alerta',
            field=models.CharField(choices=[(1, 'Clave Amarilla'), (2, 'Clave Roja')], default=2, max_length=30),
        ),
    ]
