# Generated by Django 2.2.7 on 2020-03-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0003_auto_20200110_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaemergencia',
            name='tipollamada',
            field=models.CharField(choices=[('CELULAR', 'Celular'), ('TELEFONO', 'Telefono Fijo')], max_length=10),
        ),
    ]
