# Generated by Django 2.2.7 on 2019-12-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0004_auto_20191218_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroalimentacion',
            name='idemrg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='Myapi.FichaEmergencia'),
        ),
    ]
