# Generated by Django 2.2.7 on 2020-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0005_auto_20200303_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaemergencia',
            name='tipollamada',
            field=models.CharField(choices=[(1, 'Celular'), (2, 'Telefono Fijo')], default=1, max_length=20),
        ),
    ]
