# Generated by Django 2.2.7 on 2019-12-18 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0005_auto_20191218_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroalimentacion',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reporta', to='Myapi.Estado'),
        ),
    ]
