# Generated by Django 2.2.7 on 2020-03-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0006_auto_20200303_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaemergencia',
            name='alerta',
            field=models.CharField(choices=[('AMARILLA', 'Clave Amarilla'), ('ROJA', 'Clave Roja')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaemergencia',
            name='tipollamada',
            field=models.CharField(choices=[('CELULAR', 'Celular'), ('TELEFONO', 'Telefono Fijo')], max_length=30),
        ),
    ]
