# Generated by Django 2.2.7 on 2019-12-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0006_retroalimentacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroalimentacion',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reporta', to='Myapi.Usuario'),
        ),
    ]
