# Generated by Django 2.2.7 on 2019-12-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0007_auto_20191218_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaemergencia',
            name='titulo',
            field=models.CharField(default='', max_length=150),
        ),
    ]
