# Generated by Django 2.2.7 on 2020-03-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0007_auto_20200303_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapi.Institucion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recurso', to='Myapi.Recurso'),
        ),
    ]
