# Generated by Django 2.2.7 on 2020-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0008_auto_20200304_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichaemergencia',
            old_name='coorY',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='fichaemergencia',
            old_name='coorX',
            new_name='longitud',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
